import assert from'node:assert/strict';
import{readFile}from'node:fs/promises';
import{layeredPortrait,customerPortrait,staffPortrait,rivalPortrait,officialPortrait,avatarLayerOrder}from'../src/portraits.js';
import{customerAppearances,customerCategoryAppearances,staffAppearances,rivalAppearances,assetSlots}from'../src/data/v05.js';
const wardrobe={equipped:{tops:'tops-lace',bottoms:'bottoms-flare',dresses:null,shoes:'shoes-pumps',bags:null,accessories:'accessories-pearl'},makeup:'feminine'};
const owner=layeredPortrait({player:{skin:'ナチュラル',hairStyle:'ボブ',hairColor:'ダークブラウン'},wardrobe,expression:'happy',preview:{player:{hairStyle:'ロング'},makeup:'mode'}});
assert.match(owner,/class="layer backHair"/);assert.match(owner,/class="layer makeup"/);assert.match(owner,/expression-happy/);assert.match(owner,/characters\/owner/);
assert.equal(Object.keys(customerAppearances).length,10,'主要顧客10名');assert.equal(Object.keys(staffAppearances).length,3,'初期スタッフ3名');assert.equal(Object.keys(rivalAppearances).length,3,'ライバル3名');
assert.equal(Object.keys(customerCategoryAppearances).length,5,'汎用顧客カテゴリ');assert.equal(avatarLayerOrder.length,20,'主人公20レイヤー');
assert.match(customerPortrait({id:'misaki',name:'美咲',appearance:customerAppearances.misaki},'joy'),/美咲/);assert.match(staffPortrait({id:'akari',name:'あかり',role:'店長'},'confident'),/role-店長/);assert.match(rivalPortrait('luxe','神崎レイナ'),/神崎レイナ/);assert.equal(assetSlots.stores,'assets/stores/');
assert.match(officialPortrait('owner','owner','オーナー'),/owner-base\.webp/);assert.match(officialPortrait('staff','akari','あかり'),/staff\/akari\.webp/);
assert.match(officialPortrait('customer','misaki','美咲','lg','', 'joy'),/customers\/misaki\/normal\.webp/);assert.match(officialPortrait('customer','hikari','ひかり'),/customers\/hikari\/normal\.webp/);
const gameSource=await readFile(new URL('../src/game-v03.js',import.meta.url),'utf8');
for(const rank of ['d','c','b','a'])assert.match(gameSource,new RegExp(`stores/rank-${rank}/store-rank-${rank}\\.webp`));
assert.match(gameSource,/town\/town-main\.webp/);
for(const asset of ['salon\/salon-exterior','fashion\/fashion-exterior','beauty\/beauty-exterior','cafe\/cafe-exterior','school\/school-exterior'])assert.match(gameSource,new RegExp(`town/${asset}\\.webp`));
assert.match(gameSource,/town-map-point/,'街は背景上の軽量タップポイントを使用');
assert.doesNotMatch(gameSource,/class="building-art"/,'街マップ上で施設外観カードを重ねない');
assert.match(gameSource,/has-official-art/,'正式画像のロード成功状態を明示する');
assert.match(gameSource,/customers\/\$\{c\.id\}\/\$\{expression\}\.webp\?v=55/,'全顧客の表情別正式画像を自動探索');
assert.match(gameSource,/fallbackCustomerAppearance/,'未制作顧客は年代別・ID別SVG差分を使用');
const visualCss=await readFile(new URL('../src/v05.css',import.meta.url),'utf8');
assert.match(visualCss,/\.v5-salon\.has-official-art[^}]*\.scene-object/,'正式店舗背景では旧設備を非表示');
assert.match(visualCss,/aspect-ratio:16\/10/,'スマートフォン用の街比率');
assert.match(visualCss,/adaptive-customer-portrait:not\(\.has-official-art\)/,'結果画面のSVG顧客を小さく制限');
console.log('Salon Story Ver.0.5 visual tests: OK');
