import{customers as customerTemplates}from'./data/customers.js';
import{services}from'./data/services.js';
import{staff as staffOptions}from'./data/staff.js';

const SAVE_KEY='salon-story-v01';
const VERSION=2;
const deepCopy=value=>JSON.parse(JSON.stringify(value));
const yen=value=>`${Math.round(value).toLocaleString()}円`;
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const starText=value=>'★'.repeat(value)+'☆'.repeat(5-value);
const levelThresholds=[0,100,260,480,760,1100];
const levelUnlocks={2:'バストケア',3:'毛穴洗浄',4:'ヘッドスパ',5:'高級痩身ケア'};
const faces={normal:'🙂',happy:'😊',joy:'🥰',confused:'😕',angry:'😠'};

function createGoals(day,cumulativeSales){return[
  {id:'sales7',title:'7日以内に売上5万円',description:'累計売上をあと50,000円伸ばす',type:'sales',target:50000,startValue:cumulativeSales,startDay:day,deadline:day+6,reward:{money:20000},done:false},
  {id:'rating4',title:'口コミ4.0を達成',description:'丁寧な接客で評価を上げよう',type:'rating',target:4,reward:{popularity:50},done:false},
  {id:'repeat3',title:'リピーターを3名獲得',description:'信頼関係を育てよう',type:'repeaters',target:3,reward:{money:30000},done:false}
]}

function freshState(){return{version:VERSION,day:1,money:500000,popularity:100,rating:3,salonLevel:1,xp:0,todaySales:0,staff:null,customers:deepCopy(customerTemplates),equipment:{bed:1,sofa:1,plant:1,shelf:0},ads:[],history:[],cumulativeSales:0,screen:'home',session:null,developedServices:['facial','smallface','slimming'],serviceLevels:{facial:1,smallface:1,slimming:1},reviews:[],goals:createGoals(1,0),achievements:[],flags:{sales100k:false},pendingLevelUp:null,selectedCustomer:null}}

function migrate(raw){
  const base=freshState();if(!raw)return base;
  const oldVersion=raw.version||1;
  const merged={...base,...raw,version:VERSION,equipment:{...base.equipment,...raw.equipment},flags:{...base.flags,...raw.flags},screen:'home',session:null,pendingLevelUp:null};
  merged.customers=customerTemplates.map(template=>{const old=(raw.customers||[]).find(c=>c.id===template.id)||{};return{...deepCopy(template),...old,job:old.job||template.job,counseling:deepCopy(template.counseling),reviews:old.reviews||[],lastService:old.lastService||null,favoriteService:old.favoriteService||null}});
  if(merged.staff)merged.staff={level:1,xp:0,energy:100,...merged.staff};
  if(oldVersion===1){merged.developedServices=['facial','smallface','slimming','relax','bust'];merged.serviceLevels={facial:1,smallface:1,slimming:1,relax:1,bust:1,...raw.serviceLevels}}
  merged.developedServices=merged.developedServices||base.developedServices;merged.serviceLevels=merged.serviceLevels||base.serviceLevels;merged.reviews=merged.reviews||[];merged.goals=merged.goals?.length?merged.goals:createGoals(merged.day,merged.cumulativeSales);merged.achievements=merged.achievements||[];
  return merged
}

let state=(()=>{try{return migrate(JSON.parse(localStorage.getItem(SAVE_KEY)||'null'))}catch{return freshState()}})();
let toast='';
const save=()=>localStorage.setItem(SAVE_KEY,JSON.stringify({...state,screen:'home',session:null,pendingLevelUp:null}));
function notify(message){toast=message;render();setTimeout(()=>{toast='';render()},1800)}
function spend(cost){if(state.money<cost){notify('所持金が足りません');return false}state.money-=cost;return true}
function customerRank(customer){if(customer.visits>=10&&customer.trust>=90)return'VIP';if(customer.visits>=5&&customer.trust>=60)return'常連';if(customer.visits>=2)return'リピーター';return'初回来店'}
function ratingLabel(score){if(score>=90)return{label:'✨ PERFECT!',className:'perfect'};if(score>=75)return{label:'♡ GOOD!',className:'good'};if(score>=60)return{label:'OK',className:'ok'};if(score>=40)return{label:'△ NOT BAD',className:'notbad'};return{label:'💢 BAD',className:'bad-result'}}
function serviceData(service){const level=state.serviceLevels[service.id]||1;return{...service,level,price:service.price+(level-1)*(service.id==='slimming'?1000:750),base:service.base+(level-1)*(service.id==='slimming'?5:4)}}
function availableServices(){return services.filter(service=>state.developedServices.includes(service.id)).map(serviceData)}
function canDevelopService(id){const service=services.find(item=>item.id===id);return Boolean(service&&state.salonLevel>=service.requiredLevel&&!state.developedServices.includes(id)&&state.money>=service.developmentCost)}
function developServiceById(id){const service=services.find(item=>item.id===id);if(!canDevelopService(id))return false;state.money-=service.developmentCost;state.developedServices.push(id);state.serviceLevels[id]=1;return true}
function nextLevelProgress(){if(state.salonLevel>=5)return{current:1,label:'MAX'};const start=levelThresholds[state.salonLevel-1],end=levelThresholds[state.salonLevel];return{current:clamp((state.xp-start)/(end-start),0,1),label:`${state.xp-start} / ${end-start} XP`}}
function addXP(amount){state.xp+=amount;let before=state.salonLevel;while(state.salonLevel<5&&state.xp>=levelThresholds[state.salonLevel])state.salonLevel++;if(state.salonLevel>before)state.pendingLevelUp={from:before,to:state.salonLevel,unlock:levelUnlocks[state.salonLevel]}}
function goalProgress(goal){if(goal.type==='sales')return state.cumulativeSales-goal.startValue;if(goal.type==='rating')return state.rating;if(goal.type==='repeaters')return state.customers.filter(c=>customerRank(c)!=='初回来店').length;return 0}
function checkGoals(){const completed=[];state.goals.forEach(goal=>{if(goal.done)return;const timedOut=goal.deadline&&state.day>goal.deadline;if(!timedOut&&goalProgress(goal)>=goal.target){goal.done=true;if(goal.reward.money)state.money+=goal.reward.money;if(goal.reward.popularity)state.popularity+=goal.reward.popularity;completed.push(goal)}});return completed}
function unlockAchievement(id,title){if(!state.achievements.includes(id)){state.achievements.push(id);notify(`🏆 実績解除：${title}`)}}

const navItems=[['home','🏠','ホーム'],['store','🛋️','店舗'],['staff','👩🏻','スタッフ'],['services','🫧','施術'],['ads','📣','広告'],['shop','🛍️','ショップ'],['customers','♡','カルテ'],['reviews','⭐','口コミ'],['data','📊','経営']];
function shell(content){return`<div class="shell v02"><header class="top"><div class="brand">Salon Story<small>わたしのサロン経営</small></div><div class="day">Day ${state.day}</div></header><main>${content}</main><nav class="nav">${navItems.map(([id,icon,name])=>`<button data-nav="${id}" class="${state.screen===id?'active':''}"><b>${icon}</b>${name}</button>`).join('')}</nav>${toast?`<div class="toast">${toast}</div>`:''}${state.pendingLevelUp?levelUpOverlay():''}</div>`}
function stats(){const progress=nextLevelProgress();return`<div class="stats"><div class="stat"><span>所持金</span><strong>${yen(state.money)}</strong></div><div class="stat"><span>本日の売上</span><strong>${yen(state.todaySales)}</strong></div><div class="stat"><span>店舗人気</span><strong>${state.popularity}</strong></div><div class="stat"><span>口コミ評価</span><strong>★ ${state.rating.toFixed(1)}</strong></div><div class="stat level-stat"><span>Salon Lv.${state.salonLevel}</span><strong>${progress.label}</strong><div class="bar"><i style="width:${progress.current*100}%"></i></div></div></div>`}
function goalsHTML(){return`<section class="goal-section"><div class="section-title"><h2>今日の目標</h2><span class="pill">成長チャレンジ</span></div><div class="grid">${state.goals.map(goal=>{const value=goalProgress(goal),percent=clamp(value/goal.target*100,0,100);return`<div class="card goal-card ${goal.done?'goal-done':''}"><span>${goal.done?'✅ 達成！':goal.deadline?`残り${Math.max(0,goal.deadline-state.day+1)}日`:'挑戦中'}</span><h3>${goal.title}</h3><div class="bar"><i style="width:${percent}%"></i></div><small>${typeof value==='number'&&goal.type!=='rating'?Math.floor(value).toLocaleString():Number(value).toFixed(1)} / ${goal.target.toLocaleString()}</small><p>報酬：${goal.reward.money?yen(goal.reward.money):`人気 +${goal.reward.popularity}`}</p></div>`}).join('')}</div></section>`}
function home(){const projected=Math.min(6,1+Math.floor(state.popularity/300)+state.ads.reduce((sum,ad)=>sum+ad.min,0));return`${stats()}<section class="hero game-hero"><span class="sparkle">✦</span><h1>Salon Story</h1><p>${state.staff?`${state.staff.name}と一緒に、お客様の気持ちを考える一日を始めましょう。`:'最初のスタッフを選ぶと、サロンを開店できます。'}</p><button class="primary big-action" data-action="start" ${!state.staff?'disabled':''}>営業開始　→</button></section>${!state.staff?'<div class="notice">まず下部の「スタッフ」から初期スタッフを1人採用してください。</div>':''}<div class="grid"><div class="card"><span class="pill">TODAY</span><h3>来店予定</h3><strong class="big-number">${projected}名</strong></div><div class="card"><span class="pill">STAFF</span><h3>担当スタッフ</h3><strong>${state.staff?.name||'未採用'}</strong><p>${state.staff?`Lv.${state.staff.level}・体力 ${state.staff.energy}%`:'スタッフを選択してください'}</p></div><div class="card"><span class="pill">CUSTOMER</span><h3>常連・VIP</h3><strong class="big-number">${state.customers.filter(c=>['常連','VIP'].includes(customerRank(c))).length}名</strong></div></div>${goalsHTML()}`}

function salonScene(stage='idle',customer=null){return`<div class="salon-scene stage-${stage}"><div class="room-label">SALON FLOOR</div><div class="scene-door">🚪<small>入口</small></div><div class="scene-desk">🛎️<small>受付</small></div><div class="scene-sofa">🛋️<small>待合</small></div><div class="scene-bed">🛏️<small>施術</small></div>${state.staff?`<div class="scene-staff">${state.staff.emoji}<small>${state.staff.name}</small></div>`:''}${customer?`<div class="scene-customer">👩🏻<small>${customer.name}様</small></div>`:''}</div>`}
const equipmentLabels={bed:['施術ベッド','満足度'],sofa:['待合ソファ','店舗満足度'],plant:['観葉植物','リラックス'],shelf:['商品棚','商品販売']};
function storePage(){return`<div class="section-title"><h2>わたしの店舗</h2><span class="pill">1号店</span></div>${salonScene()}<div class="grid">${Object.entries(equipmentLabels).map(([id,label])=>`<div class="card"><h3>${label[0]} Lv.${state.equipment[id]}</h3><div class="row"><span>${label[1]}</span><b>${id==='shelf'?(state.equipment[id]?'解禁':'未解禁'):'強化中'}</b></div></div>`).join('')}</div>`}
function ability(staff){return[['技術','tech'],['接客','service'],['営業','sales'],['速度','speed']].map(([name,key])=>`<div class="row"><span>${name}</span><b>${staff[key]}</b></div><div class="bar"><i style="width:${staff[key]}%"></i></div>`).join('')}
function staffPage(){if(!state.staff)return`<div class="section-title"><h2>初期スタッフ採用</h2><span class="pill">1人選択</span></div><div class="grid">${staffOptions.map(staff=>`<div class="card staff-pick"><div class="staff-emoji">${staff.emoji}</div><h3>${staff.name}</h3><span class="pill">${staff.trait}</span>${ability(staff)}<p>月給 ${yen(staff.salary)}</p><button class="primary wide" data-hire="${staff.id}">この人を採用</button></div>`).join('')}</div>`;const next=state.staff.level*50;return`<div class="section-title"><h2>スタッフ</h2><span class="pill">在籍1名</span></div><div class="grid"><div class="card"><div class="staff-emoji">${state.staff.emoji}</div><h2>${state.staff.name} <small>Lv.${state.staff.level}</small></h2><span class="pill">${state.staff.trait}</span><div class="row"><span>経験値</span><b>${state.staff.xp}/${next}</b></div><div class="bar"><i style="width:${clamp(state.staff.xp/next*100,0,100)}%"></i></div><div class="row"><span>体力</span><b>${state.staff.energy}%</b></div></div><div class="card">${ability(state.staff)}</div><div class="card"><h3>研修</h3>${[['service','接客研修',10000],['tech','技術研修',15000],['sales','営業研修',12000],['speed','スピード研修',10000]].map(([key,name,cost])=>`<div class="row"><span>${name}<small> +3〜5</small></span><button class="soft" data-train="${key}" data-cost="${cost}">${yen(cost)}</button></div>`).join('')}</div></div>`}

function serviceCard(service,mode){const s=serviceData(service),developed=state.developedServices.includes(s.id),unlocked=state.salonLevel>=s.requiredLevel;return`<div class="card service-management ${!unlocked?'locked':''}"><div class="service-icon">${s.icon}</div><h3>${s.name} ${developed?`<small>Lv.${s.level}</small>`:''}</h3>${developed?`<div class="row"><span>価格</span><b>${yen(s.price)}</b></div><div class="row"><span>基本効果</span><b>${s.base}</b></div><p>適性：${s.matches.join('・')}</p><button class="soft wide" data-upgrade="${s.id}" ${s.level>=3?'disabled':''}>${s.level>=3?'最大Lv.':'強化 '+yen(20000+s.level*20000)}</button>`:unlocked?`<p>開発費 ${yen(s.developmentCost)}</p><button class="primary wide" data-develop="${s.id}">開発する</button>`:`<p>🔒 Salon Lv.${s.requiredLevel}で開発可能</p>`}</div>`}
function servicesPage(){const current=services.filter(s=>state.developedServices.includes(s.id)),available=services.filter(s=>!state.developedServices.includes(s.id)&&state.salonLevel>=s.requiredLevel),locked=services.filter(s=>state.salonLevel<s.requiredLevel);return`<div class="section-title"><h2>施術メニュー</h2><span class="pill">Salon Lv.${state.salonLevel}</span></div><h3>現在提供中</h3><div class="grid">${current.map(s=>serviceCard(s,'current')).join('')}</div><h3 class="group-title">開発可能</h3>${available.length?`<div class="grid">${available.map(s=>serviceCard(s,'available')).join('')}</div>`:'<div class="empty card">現在開発できる新メニューはありません</div>'}<h3 class="group-title">未解禁</h3><div class="grid">${locked.map(s=>serviceCard(s,'locked')).join('')}</div>`}

const adsData=[['flyer','チラシ',10000,'翌日新規客 +1〜3',1,3],['sns','SNS広告',30000,'翌日新規客 +2〜5',2,5],['review','口コミキャンペーン',20000,'口コミ投稿率アップ',0,0]];
function adsPage(){return`<div class="section-title"><h2>広告</h2><span class="pill">翌日の営業に反映</span></div><div class="grid">${adsData.map(([id,name,cost,effect,min,max])=>`<div class="card"><h3>${id==='sns'?'📱':id==='review'?'⭐':'📄'} ${name}</h3><p>${effect}</p><strong>${yen(cost)}</strong><p><button class="primary wide" data-ad="${id}" ${state.ads.some(ad=>ad.id===id)?'disabled':''}>${state.ads.some(ad=>ad.id===id)?'設定済み':'広告を出す'}</button></p></div>`).join('')}</div>`}
const shopItems=[['bed','高級施術ベッド',100000,'施術満足度 +5',3],['sofa','高級ソファ',50000,'店舗満足度 +3',2],['plant','観葉植物',15000,'リラックス補正 +2',2],['shelf','商品棚',30000,'商品販売機能解禁',1]];
function shopPage(){return`<div class="section-title"><h2>ショップ</h2><span class="pill">${yen(state.money)}</span></div><div class="grid">${shopItems.map(([id,name,cost,effect,level])=>`<div class="card"><h3>${name}</h3><p>${effect}</p><strong>${yen(cost)}</strong><p><button class="primary wide" data-buy="${id}" ${state.equipment[id]>=level?'disabled':''}>${state.equipment[id]>=level?'購入済み':'購入する'}</button></p></div>`).join('')}</div>`}

function customersPage(){return`<div class="section-title"><h2>顧客カルテ</h2><span class="pill">全${state.customers.length}名</span></div><div class="grid">${state.customers.map(customer=>`<div class="card chart-card"><div class="chart-head"><span class="mini-avatar">${customer.trust>=70?'😊':'🙂'}</span><div><h3>${customer.name} <small>${customer.age}歳</small></h3><span class="rank rank-${customerRank(customer)}">${customerRank(customer)}</span></div></div><p>${customer.job}・${customer.personality}</p><div class="row"><span>お悩み</span><b>${customer.concern}</b></div><div class="row"><span>信頼度</span><b>${customer.trust}</b></div><button class="soft wide" data-chart="${customer.id}">カルテを見る</button></div>`).join('')}</div>`}
function customerChart(){const c=state.customers.find(x=>x.id===state.selectedCustomer);if(!c)return customersPage();return`<button class="soft back-button" data-nav="customers">← 顧客一覧へ</button><div class="card full-chart"><div class="chart-head"><span class="large-avatar">${c.trust>=90?'🥰':c.trust>=60?'😊':'🙂'}</span><div><h1>${c.name} <small>${c.age}歳</small></h1><span class="rank rank-${customerRank(c)}">${customerRank(c)}</span></div></div><div class="chart-grid"><div><span>職業</span><b>${c.job}</b></div><div><span>性格</span><b>${c.personality}</b></div><div><span>悩み</span><b>${c.concern}</b></div><div><span>予算</span><b>${yen(c.budget)}</b></div><div><span>美容意識</span><b>${'★'.repeat(c.beauty)}</b></div><div><span>信頼度</span><b>${c.trust}</b></div><div><span>来店回数</span><b>${c.visits}回</b></div><div><span>累計利用額</span><b>${yen(c.totalSpent)}</b></div><div><span>最後の施術</span><b>${c.lastService||'—'}</b></div><div><span>お気に入り施術</span><b>${c.favoriteService||'—'}</b></div></div><h3>口コミ履歴</h3>${c.reviews.length?c.reviews.slice().reverse().map(r=>`<div class="review-mini"><b>${starText(r.star)}</b><span>${r.text}</span></div>`).join(''):'<div class="empty">まだ口コミはありません</div>'}</div>`}
function reviewsPage(){return`<div class="section-title"><h2>お客様の口コミ</h2><span class="pill">${state.reviews.length}件</span></div>${state.reviews.length?`<div class="review-list">${state.reviews.slice().reverse().map(r=>`<div class="card review-card"><div><b class="stars small-stars">${starText(r.star)}</b><span>Day ${r.day}</span></div><h3>${r.customer}</h3><p>「${r.text}」</p></div>`).join('')}</div>`:'<div class="card empty">口コミが投稿されると、ここに残ります</div>'}`}
function dataPage(){const history=state.history.slice(-10),max=Math.max(...history.map(item=>item.sales),1);return`<div class="section-title"><h2>経営データ</h2><span class="pill">累計売上 ${yen(state.cumulativeSales)}</span></div><div class="card"><h3>日別売上</h3>${history.length?`<div class="chart">${history.map(item=>`<div style="height:${item.sales/max*100}%" title="${yen(item.sales)}"><span>D${item.day}</span></div>`).join('')}</div>`:'<div class="empty">営業後にグラフが表示されます</div>'}</div><div class="grid data-cards"><div class="card"><h3>累計来店数</h3><strong class="big-number">${state.history.reduce((sum,x)=>sum+x.guests,0)}名</strong></div><div class="card"><h3>平均満足度</h3><strong class="big-number">${state.history.length?Math.round(state.history.reduce((sum,x)=>sum+x.avg,0)/state.history.length):0}</strong></div><div class="card"><h3>実績</h3><strong class="big-number">${state.achievements.length}個</strong></div></div><p><button class="soft danger" data-action="reset">セーブデータを削除</button></p>`}

function startDay(){let count=Math.min(5,1+Math.floor(state.popularity/300));state.ads.forEach(ad=>count+=ad.min+Math.floor(Math.random()*(ad.max-ad.min+1)));count=clamp(count,1,6);const repeaters=state.customers.filter(c=>c.visits>0&&Math.random()<c.repeatChance/100);const shuffled=[...state.customers].sort(()=>Math.random()-.5);const ids=[...new Set([...repeaters,...shuffled].map(c=>c.id))].slice(0,count);state.todaySales=0;if(state.staff)state.staff.energy=100;state.session={queue:ids,index:0,results:[],phase:'arrival',choice:null,xp:0,startedLevel:state.salonLevel};state.screen='play';render();setTimeout(()=>{if(state.screen==='play'&&state.session?.phase==='arrival'){state.session.phase='counsel';render()}},900)}
function currentCustomer(){return state.customers.find(c=>c.id===state.session.queue[state.session.index])}
function playPage(){
  const c=currentCustomer();
  if(!c)return'';
  const phase=state.session.phase;
  if(phase==='arrival'){
    return`${salonScene('arrival',c)}<div class="arrival-banner">✨ ${c.name}様が来店しました！</div>`;
  }
  if(phase==='reaction'){
    const choice=state.session.choice;
    return`${salonScene('sofa',c)}<div class="card reaction-card"><div class="reaction-face">${faces[choice.face]}</div><h2>${c.name}様</h2><div class="speech">「${choice.response}」</div><div class="change-line"><span>信頼度</span><b>${choice.beforeTrust} → <em>${c.trust}</em></b><strong class="${choice.trust>=0?'plus':'minus'}">${choice.trust>=0?'+':''}${choice.trust}</strong></div><div class="change-line"><span>満足度補正</span><strong class="${choice.satisfaction>=0?'plus':'minus'}">${choice.satisfaction>=0?'+':''}${choice.satisfaction}</strong></div><button class="primary wide sticky-action" data-action="chooseService">施術を提案する</button></div>`;
  }
  if(phase==='service'){
    const cards=availableServices().map(service=>`<button class="service ${!service.matches.includes(c.concern)?'bad':''}" data-service="${service.id}"><div class="service-icon">${service.icon}</div><b>${service.name} Lv.${service.level}</b><div>${yen(service.price)}・${service.time}分</div>${service.matches.includes(c.concern)?'<span class="pill">お悩みに適合</span>':''}</button>`).join('');
    return`${salonScene('sofa',c)}<div class="section-title"><h2>${c.name}様への施術提案</h2><span class="pill">予算 ${yen(c.budget)}</span></div><p>お悩み「${c.concern}」に合う施術を選びましょう。</p><div class="service-list">${cards}</div>`;
  }
  if(phase==='treatment'){
    return`${salonScene('treatment',c)}<div class="treatment"><div>🫧　✨　💆🏻‍♀️　✨</div><h2>施術中…</h2><button class="soft" data-action="skipTreatment">スキップ</button></div>`;
  }
  const choices=c.counseling.map((choice,index)=>`<button class="choice" data-counsel="${index}"><b>${'ABCD'[index]}.</b> ${choice[1]}</button>`).join('');
  return`${salonScene('sofa',c)}<div class="section-title"><h2>カウンセリング</h2><span class="pill">${state.session.index+1}/${state.session.queue.length}人目</span></div><div class="card customer"><div class="avatar">${faces.normal}</div><div><h2>${c.name} <small>${c.age}歳・${c.job}</small></h2><div><span class="pill">${c.personality}</span> <span class="pill">信頼度 ${c.trust}</span></div><div class="speech">「${c.dialogue}」</div></div></div><h3>どう答える？</h3><div class="choices">${choices}</div>`;
}
function chooseCounsel(index){const c=currentCustomer(),choice=c.counseling[index],before=c.trust;let trust=choice[3],satisfaction=choice[4];if(choice[0]==='course'&&c.visits>0&&c.trust>=80){trust=Math.max(3,trust);satisfaction=Math.max(4,satisfaction)}if(state.staff.trait==='接客上手'&&c.personality==='慎重')trust+=2;c.trust=clamp(c.trust+trust,0,100);state.session.choice={key:choice[0],response:choice[2],trust,satisfaction,face:choice[5],beforeTrust:before};state.session.phase='reaction';render()}
function selectService(id){state.session.selectedService=id;state.session.phase='treatment';render();state.session.treatmentTimer=setTimeout(finishTreatment,1400)}
function finishTreatment(){if(!state.session||state.session.phase!=='treatment')return;clearTimeout(state.session.treatmentTimer);const c=currentCustomer(),service=availableServices().find(s=>s.id===state.session.selectedService),choice=state.session.choice;const trustBefore=choice.beforeTrust,repeatBefore=c.repeatChance,rankBefore=customerRank(c),energyPenalty=state.staff.energy<50?Math.round((50-state.staff.energy)/8):0,match=service.matches.includes(c.concern)?25:0,equipment=(state.equipment.bed===3?5:state.equipment.bed===2?3:0)+(state.equipment.sofa>1?3:0)+(state.equipment.plant>1?2:0),pricePenalty=service.price>c.budget?c.priceSensitivity*4:0;const score=clamp(Math.round(service.base+state.staff.service*.22+state.staff.tech*.22+match+equipment+choice.satisfaction-pricePenalty-energyPenalty),0,100),rating=ratingLabel(score),star=score>=90?5:score>=75?4:score>=60?3:score>=40?2:1,serviceTrust=score>=90?5:score>=75?3:score<40?-4:score<60?-1:1;c.trust=clamp(c.trust+serviceTrust,0,100);c.visits++;c.totalSpent+=service.price;c.lastService=service.name;c.serviceCounts=c.serviceCounts||{};c.serviceCounts[service.id]=(c.serviceCounts[service.id]||0)+1;c.favoriteService=services.find(s=>s.id===Object.entries(c.serviceCounts).sort((a,b)=>b[1]-a[1])[0][0])?.name||service.name;c.repeatChance=clamp(20+Math.floor(score*.35)+Math.floor(c.trust*.25)+(star-3)*3,0,90);c.isRepeater=c.visits>=2;const rankAfter=customerRank(c),becameRepeater=rankBefore==='初回来店'&&rankAfter==='リピーター',becameVIP=rankBefore!=='VIP'&&rankAfter==='VIP';let xp=10+(score>=90?30:score>=75?15:0)+(becameRepeater?20:0)+(becameVIP?100:0);addXP(xp);state.session.xp+=xp;state.staff.energy=clamp(state.staff.energy-(10+Math.floor(Math.random()*11)),0,100);state.staff.xp+=10;let staffLevelUp=false;while(state.staff.level<20&&state.staff.xp>=state.staff.level*50){state.staff.xp-=state.staff.level*50;state.staff.level++;const key=['tech','service','sales','speed'][Math.floor(Math.random()*4)];state.staff[key]=clamp(state.staff[key]+2,0,100);staffLevelUp=true}state.money+=service.price;state.todaySales+=service.price;state.cumulativeSales+=service.price;const popGain=score>=90?8:score>=75?5:score>=60?2:score<40?-5:0;state.popularity=Math.max(0,state.popularity+popGain);const reactions=score>=90?['想像以上です！また絶対にお願いします♡','悩みにぴったりで、とても嬉しいです！']:score>=75?['変化が分かって嬉しいです！またお願いします。','私に合う提案をしてくれて安心できました。']:score>=60?['すっきりしました。ありがとうございました。']:score>=40?['施術は悪くなかったけど、少し期待と違いました。']:['今日は私には合わなかったかもしれません…。'];const response=reactions[Math.floor(Math.random()*reactions.length)];state.session.results.push({customer:c.name,service:service.name,sales:service.price,score,star,label:rating.label,className:rating.className,response,face:score>=90?'joy':score>=75?'happy':score<40?'angry':score<60?'confused':'normal',trustBefore,trustAfter:c.trust,repeatBefore,repeatAfter:c.repeatChance,popGain,xp,rankBefore,rankAfter,staffLevelUp});state.screen='serviceResult';render()}
function serviceResultPage(){const r=state.session.results[state.session.results.length-1];return`<div class="card result game-result ${r.className}"><div class="result-label">${r.label}</div><div class="reaction-face">${faces[r.face]}</div><h2>${r.customer}様</h2><div class="speech">「${r.response}」</div><div class="score" style="--score:${r.score}"><strong>${r.score}</strong></div><div class="change-line"><span>信頼度</span><b>${r.trustBefore} → <em>${r.trustAfter}</em></b></div><div class="change-line"><span>売上</span><strong class="plus">+${yen(r.sales)}</strong></div><div class="change-line"><span>店舗人気</span><strong class="${r.popGain>=0?'plus':'minus'}">${r.popGain>=0?'+':''}${r.popGain}</strong></div><div class="change-line"><span>次回来店率</span><b>${r.repeatBefore}% → <em>${r.repeatAfter}%</em></b></div><div class="change-line"><span>Salon XP</span><strong class="plus">+${r.xp} XP</strong></div>${r.rankBefore!==r.rankAfter?`<div class="rank-up">🎊 顧客ランクUP！ ${r.rankAfter}</div>`:''}${r.staffLevelUp?`<div class="rank-up">🎉 ${state.staff.name}がLv.${state.staff.level}になりました！</div>`:''}<button class="primary wide sticky-action" data-action="nextCustomer">${state.session.index+1<state.session.queue.length?'次のお客様へ':'閉店する'}</button></div>`}
function nextCustomer(){state.session.index++;if(state.session.index>=state.session.queue.length){closeDay();return}state.session.phase='arrival';state.session.choice=null;state.screen='play';render();setTimeout(()=>{if(state.screen==='play'&&state.session?.phase==='arrival'){state.session.phase='counsel';render()}},900)}
function closeDay(){const results=state.session.results,average=Math.round(results.reduce((sum,x)=>sum+x.score,0)/Math.max(results.length,1)),reviewRate=state.ads.some(ad=>ad.id==='review')?0.85:0.5;const posted=results.filter(()=>Math.random()<reviewRate);posted.forEach(result=>{const review={day:state.day,customer:result.customer,star:result.star,text:result.response};state.reviews.push(review);const customer=state.customers.find(c=>c.name===result.customer);customer.reviews.push(review)});if(posted.length){const averageStars=posted.reduce((sum,x)=>sum+x.star,0)/posted.length;state.rating=clamp(state.rating*.8+averageStars*.2,1,5)}let expenses=0;if(state.day%30===0&&state.staff){expenses=state.staff.salary;state.money-=expenses}if(state.cumulativeSales>=100000&&!state.flags.sales100k){state.flags.sales100k=true;addXP(50);unlockAchievement('sales100k','人気サロンへの第一歩')}if(results.length)unlockAchievement('firstCustomer','はじめてのお客様');const goals=checkGoals();const entry={day:state.day,guests:results.length,sales:state.todaySales,expenses,profit:state.todaySales-expenses,avg:average,reviews:posted.length,repeaters:results.filter(r=>r.rankAfter!=='初回来店').length,popDelta:results.reduce((sum,r)=>sum+r.popGain,0),xp:state.session.xp,goals:goals.map(g=>g.title)};state.history.push(entry);state.ads=[];state.staff.energy=100;state.screen='dayResult';save();render()}
function dayResultPage(){const result=state.history[state.history.length-1];return`<div class="section-title"><h2>Day ${result.day} 営業結果</h2><span class="pill">おつかれさまでした</span></div><div class="card result daily-result"><div class="coin-burst">🪙 +${yen(result.sales)}</div><h2>本日の成長</h2><div class="row"><span>来店人数</span><b>${result.guests}名</b></div><div class="row"><span>施術売上</span><b>${yen(result.sales)}</b></div><div class="row"><span>給与・支出</span><b>−${yen(result.expenses)}</b></div><div class="row"><span>本日の利益</span><b>${yen(result.profit)}</b></div><div class="row"><span>平均満足度</span><b>${result.avg}</b></div><div class="row"><span>口コミ</span><b>${result.reviews}件</b></div><div class="row"><span>Salon XP</span><b>+${result.xp}</b></div>${result.goals.length?`<div class="goal-complete">🎯 目標達成！<br>${result.goals.join('<br>')}</div>`:''}<button class="primary wide sticky-action" data-action="nextDay">翌日へ進む</button></div>`}
function levelUpOverlay(){const level=state.pendingLevelUp;return`<div class="level-overlay"><div class="level-modal"><div class="level-sparkles">✨ 🎉 ✨</div><p>SALON LEVEL UP!</p><h1>Lv.${level.to}</h1><div class="unlock-box">新メニュー<br><strong>「${level.unlock}」</strong><br>が開発可能になりました！</div><button class="primary wide" data-action="closeLevelUp">確認する</button></div></div>`}

function render(){let content={home,store:storePage,staff:staffPage,services:servicesPage,ads:adsPage,shop:shopPage,customers:customersPage,customerChart,reviews:reviewsPage,data:dataPage,play:playPage,serviceResult:serviceResultPage,dayResult:dayResultPage}[state.screen]?.()||home();document.querySelector('#app').innerHTML=shell(content);bind()}
function bind(){
  document.querySelectorAll('[data-nav]').forEach(button=>button.onclick=()=>{state.screen=button.dataset.nav;render()});
  document.querySelector('[data-action="start"]')?.addEventListener('click',startDay);
  document.querySelectorAll('[data-hire]').forEach(button=>button.onclick=()=>{state.staff={level:1,xp:0,energy:100,...deepCopy(staffOptions.find(s=>s.id===button.dataset.hire))};save();notify(`${state.staff.name}を採用しました！`)});
  document.querySelectorAll('[data-train]').forEach(button=>button.onclick=()=>{if(spend(Number(button.dataset.cost))){const key=button.dataset.train,before=state.staff[key],gain=3+Math.floor(Math.random()*3);state.staff[key]=clamp(before+gain,0,100);save();notify(`${key==='service'?'接客':key==='tech'?'技術':key==='sales'?'営業':'速度'} ${before} → ${state.staff[key]}`)}});
  document.querySelectorAll('[data-ad]').forEach(button=>button.onclick=()=>{const ad=adsData.find(item=>item[0]===button.dataset.ad);if(spend(ad[2])){state.ads.push({id:ad[0],min:ad[4],max:ad[5]});save();notify(`${ad[1]}を設定しました！`)}});
  document.querySelectorAll('[data-buy]').forEach(button=>button.onclick=()=>{const item=shopItems.find(x=>x[0]===button.dataset.buy);if(spend(item[2])){state.equipment[item[0]]=item[4];save();notify(`${item[1]}を購入しました！`)}});
  document.querySelectorAll('[data-develop]').forEach(button=>button.onclick=()=>{const service=services.find(s=>s.id===button.dataset.develop);if(developServiceById(service.id)){save();notify(`新メニュー「${service.name}」を開発しました！`)}else notify('開発条件または所持金を確認してください')});
  document.querySelectorAll('[data-upgrade]').forEach(button=>button.onclick=()=>{const id=button.dataset.upgrade,current=state.serviceLevels[id]||1,cost=20000+current*20000;if(spend(cost)){state.serviceLevels[id]=current+1;save();notify(`${services.find(s=>s.id===id).name} Lv.${current} → Lv.${current+1}`)}});
  document.querySelectorAll('[data-chart]').forEach(button=>button.onclick=()=>{state.selectedCustomer=button.dataset.chart;state.screen='customerChart';render()});
  document.querySelectorAll('[data-counsel]').forEach(button=>button.onclick=()=>chooseCounsel(Number(button.dataset.counsel)));
  document.querySelector('[data-action="chooseService"]')?.addEventListener('click',()=>{state.session.phase='service';render()});
  document.querySelectorAll('[data-service]').forEach(button=>button.onclick=()=>selectService(button.dataset.service));
  document.querySelector('[data-action="skipTreatment"]')?.addEventListener('click',finishTreatment);
  document.querySelector('[data-action="nextCustomer"]')?.addEventListener('click',nextCustomer);
  document.querySelector('[data-action="nextDay"]')?.addEventListener('click',()=>{state.day++;state.todaySales=0;state.session=null;state.screen='home';save();render()});
  document.querySelector('[data-action="closeLevelUp"]')?.addEventListener('click',()=>{state.pendingLevelUp=null;save();render()});
  document.querySelector('[data-action="reset"]')?.addEventListener('click',()=>{if(confirm('すべてのセーブデータを削除しますか？')){localStorage.removeItem(SAVE_KEY);state=freshState();render()}})
}

window.__SALON_STORY_TEST__={freshState,migrate,customerRank,ratingLabel,serviceData,addXP,canDevelopService,developServiceById,getState:()=>state,setState:value=>{state=value}};
render();
if('serviceWorker'in navigator)navigator.serviceWorker.getRegistrations().then(items=>items.forEach(item=>item.unregister())).catch(()=>{});
if('caches'in window)caches.keys().then(keys=>keys.filter(key=>key.startsWith('salon-story')).forEach(key=>caches.delete(key))).catch(()=>{});
