import './style.css';import{customers as baseCustomers}from'./data/customers.js';import{services}from'./data/services.js';import{staff as staffOptions}from'./data/staff.js';
const KEY='salon-story-v01';const copy=x=>JSON.parse(JSON.stringify(x));
const initial=()=>({day:1,money:500000,popularity:100,rating:3,salonLevel:1,xp:0,todaySales:0,staff:null,customers:copy(baseCustomers),equipment:{bed:1,sofa:1,plant:1,shelf:0},ads:[],history:[],cumulativeSales:0,screen:'home',session:null});
let state=(()=>{try{return Object.assign(initial(),JSON.parse(localStorage.getItem(KEY))||{})}catch{return initial()}})();let toast='';
const yen=n=>`${Math.round(n).toLocaleString()}円`,stars=n=>'★'.repeat(n)+'☆'.repeat(5-n);const save=()=>localStorage.setItem(KEY,JSON.stringify({...state,screen:'home',session:null}));
function notify(s){toast=s;render();setTimeout(()=>{toast='';render()},1800)}function nav(screen){state.screen=screen;render()}function spend(cost){if(state.money<cost){notify('所持金が足りません');return false}state.money-=cost;save();return true}
const navs=[['home','🏠','ホーム'],['store','🛋️','店舗'],['staff','👩🏻','スタッフ'],['services','🫧','施術'],['ads','📣','広告'],['shop','🛍️','ショップ'],['customers','♡','顧客'],['data','📊','経営']];
function layout(body){return`<div class="shell"><header class="top"><div class="brand">Salon Story<small>わたしのサロン経営</small></div><div class="day">Day ${state.day}</div></header><main>${body}</main><nav class="nav">${navs.map(([id,ic,n])=>`<button data-nav="${id}" class="${state.screen===id?'active':''}"><b>${ic}</b>${n}</button>`).join('')}</nav>${toast?`<div class="toast">${toast}</div>`:''}</div>`}
function stats(){return`<div class="stats"><div class="stat"><span>所持金</span><strong>${yen(state.money)}</strong></div><div class="stat"><span>本日の売上</span><strong>${yen(state.todaySales)}</strong></div><div class="stat"><span>店舗人気</span><strong>${state.popularity}</strong></div><div class="stat"><span>口コミ評価</span><strong>★ ${state.rating.toFixed(1)}</strong></div><div class="stat"><span>サロンLv.</span><strong>${state.salonLevel}</strong></div></div>`}
function home(){const projected=Math.min(5,1+Math.floor(state.popularity/300)+(state.ads.reduce((a,x)=>a+x.min,0)||0));return`${stats()}<section class="hero"><h1>Your salon, your story.</h1><p>${state.staff?`${state.staff.name}と一緒に、お客様一人ひとりに寄り添う一日を始めましょう。`:'最初のスタッフを選ぶと、サロンを開店できます。'}</p><button class="primary" data-action="start" ${!state.staff?'disabled':''}>営業開始　→</button></section>${!state.staff?'<div class="notice">まず「スタッフ」から初期スタッフを1人採用してください。</div>':''}<div class="grid"><div class="card"><span class="pill">TODAY</span><h3>来店予定</h3><strong style="font-size:32px">${projected}名</strong></div><div class="card"><span class="pill">STAFF</span><h3>担当スタッフ</h3><strong>${state.staff?.name||'未採用'}</strong><p>${state.staff?.trait||'スタッフを選択してください'}</p></div><div class="card"><span class="pill">NEXT</span><h3>次の給与日</h3><strong>Day ${Math.ceil(state.day/30)*30}</strong><p>${state.staff?yen(state.staff.salary):'—'}</p></div></div>`}
function staffPage(){return`<div class="section-title"><h2>スタッフ</h2><span class="pill">${state.staff?'在籍 1名':'初期採用'}</span></div>${state.staff?staffDetail():`<p>一緒に働く最初のスタッフを選びましょう。採用後の変更はできません。</p><div class="grid">${staffOptions.map(s=>`<div class="card staff-pick"><div style="font-size:48px">${s.emoji}</div><h3>${s.name}</h3><span class="pill">${s.trait}</span>${ability(s)}<p>月給 ${yen(s.salary)}</p><button class="primary" data-hire="${s.id}">この人を採用</button></div>`).join('')}</div>`}`}
function ability(s){return[['技術','tech'],['接客','service'],['営業','sales'],['速度','speed']].map(([n,k])=>`<div class="row"><span>${n}</span><b>${s[k]}</b></div><div class="bar"><i style="width:${s[k]}%"></i></div>`).join('')}
function staffDetail(){return`<div class="grid"><div class="card"><div style="font-size:55px">${state.staff.emoji}</div><h2>${state.staff.name}</h2><span class="pill">${state.staff.trait}</span><p>月給 ${yen(state.staff.salary)}</p></div><div class="card">${ability(state.staff)}</div><div class="card"><h3>研修</h3>${[['service','接客研修',10000],['tech','技術研修',15000],['sales','営業研修',12000],['speed','スピード研修',10000]].map(x=>`<div class="row"><span>${x[1]}<small> +3〜5</small></span><button class="soft" data-train="${x[0]}" data-cost="${x[2]}">${yen(x[2])}</button></div>`).join('')}</div></div>`}
function servicesPage(){return`<div class="section-title"><h2>施術メニュー</h2><span class="pill">全${services.length}種</span></div><div class="grid">${services.map(s=>`<div class="card"><div style="font-size:35px">${s.icon}</div><h3>${s.name}</h3><div class="row"><span>価格</span><b>${yen(s.price)}</b></div><div class="row"><span>時間</span><b>${s.time}分</b></div><p>適性：${s.matches.join('・')}</p></div>`).join('')}</div>`}
const eq={bed:['施術ベッド','満足度',state.equipment.bed===1?'±0':state.equipment.bed===2?'+3':'+5'],sofa:['待合ソファ','店舗満足度',state.equipment.sofa>1?'+3':'±0'],plant:['観葉植物','リラックス',state.equipment.plant>1?'+2':'±0'],shelf:['商品棚','商品販売',state.equipment.shelf?'解禁':'未解禁']};
function store(){return`<div class="section-title"><h2>わたしの店舗</h2><span class="pill">1号店</span></div><div class="hero" style="background:linear-gradient(135deg,#ead4c7,#c68e91);min-height:180px"><div style="font-size:55px">🛎️　🛋️　🌿　🛏️</div><h2>Salon Story</h2></div><div class="grid">${Object.entries(eq).map(([k,v])=>`<div class="card"><h3>${v[0]} Lv.${state.equipment[k]}</h3><div class="row"><span>${v[1]}</span><b>${v[2]}</b></div></div>`).join('')}</div>`}
const adList=[['flyer','チラシ',10000,'翌日新規客 +1〜3',1,3],['sns','SNS広告',30000,'翌日新規客 +2〜5',2,5],['review','口コミキャンペーン',20000,'口コミ投稿率アップ',0,0]];
function ads(){return`<div class="section-title"><h2>広告</h2><span class="pill">翌日の営業に反映</span></div><div class="grid">${adList.map(a=>`<div class="card"><h3>${a[0]==='sns'?'📱':a[0]==='review'?'⭐':'📄'} ${a[1]}</h3><p>${a[3]}</p><strong>${yen(a[2])}</strong><p><button class="primary" data-ad="${a[0]}" ${state.ads.some(x=>x.id===a[0])?'disabled':''}>${state.ads.some(x=>x.id===a[0])?'設定済み':'広告を出す'}</button></p></div>`).join('')}</div>`}
const shopItems=[['bed','高級施術ベッド',100000,'施術満足度 +5',3],['sofa','高級ソファ',50000,'店舗満足度 +3',2],['plant','観葉植物',15000,'リラックス補正 +2',2],['shelf','商品棚',30000,'商品販売機能解禁',1]];
function shop(){return`<div class="section-title"><h2>ショップ</h2><span class="pill">所持金 ${yen(state.money)}</span></div><div class="grid">${shopItems.map(x=>`<div class="card"><h3>${x[1]}</h3><p>${x[3]}</p><strong>${yen(x[2])}</strong><p><button class="primary" data-buy="${x[0]}" ${state.equipment[x[0]]>=x[4]?'disabled':''}>${state.equipment[x[0]]>=x[4]?'購入済み':'購入する'}</button></p></div>`).join('')}</div>`}
function customers(){return`<div class="section-title"><h2>顧客一覧</h2><span class="pill">リピーター ${state.customers.filter(c=>c.isRepeater).length}名</span></div><div class="grid">${state.customers.map(c=>`<div class="card"><h3>♡ ${c.name} <small>${c.age}歳</small></h3><span class="pill">${c.concern}</span><div class="row"><span>信頼度</span><b>${c.trust}</b></div><div class="row"><span>来店回数</span><b>${c.visits}回</b></div><div class="row"><span>累計利用</span><b>${yen(c.totalSpent)}</b></div></div>`).join('')}</div>`}
function data(){const h=state.history.slice(-10),max=Math.max(...h.map(x=>x.sales),1);return`<div class="section-title"><h2>経営データ</h2><span class="pill">累計売上 ${yen(state.cumulativeSales)}</span></div><div class="card"><h3>日別売上</h3>${h.length?`<div class="chart">${h.map(x=>`<div style="height:${x.sales/max*100}%" title="${yen(x.sales)}"><span>D${x.day}</span></div>`).join('')}</div>`:'<div class="empty">営業をするとグラフが表示されます</div>'}</div><div class="grid" style="margin-top:14px"><div class="card"><h3>累計来店数</h3><strong style="font-size:30px">${state.history.reduce((a,x)=>a+x.guests,0)}名</strong></div><div class="card"><h3>平均満足度</h3><strong style="font-size:30px">${state.history.length?Math.round(state.history.reduce((a,x)=>a+x.avg,0)/state.history.length):0}</strong></div><div class="card"><h3>累計利益</h3><strong style="font-size:30px">${yen(state.history.reduce((a,x)=>a+x.profit,0))}</strong></div></div><p><button class="soft danger" data-action="reset">セーブデータを削除</button></p>`}
function startDay(){let count=Math.min(5,1+Math.floor(state.popularity/300));state.ads.forEach(a=>count+=a.min+Math.floor(Math.random()*(a.max-a.min+1)));count=Math.min(6,Math.max(1,count));let pool=[...state.customers].sort(()=>Math.random()-.5);state.customers.filter(c=>c.isRepeater&&Math.random()<c.repeatChance/100).forEach(c=>{if(!pool.slice(0,count).some(x=>x.id===c.id))pool.unshift(c)});state.session={queue:pool.slice(0,count).map(x=>x.id),index:0,results:[],counsel:null};state.todaySales=0;state.screen='play';render()}
const counselChoices=[['gentle','まずは今日1回だけ試してみましょう',8,5],['sales','お得な回数コースがおすすめです',-3,2],['home','ホームケアも組み合わせましょう',4,3],['listen','今日は相談だけでも大丈夫ですよ',10,0]];
function current(){return state.customers.find(c=>c.id===state.session.queue[state.session.index])}
function play(){const c=current();if(!c)return closeDay();if(!state.session.counsel)return`<div class="section-title"><h2>カウンセリング</h2><span class="pill">${state.session.index+1} / ${state.session.queue.length}人目</span></div><div class="card customer"><div class="avatar">👩🏻</div><div><h2>${c.name} <small>${c.age}歳</small></h2><span class="pill">お悩み：${c.concern}</span><div class="speech">「${c.dialogue}」</div></div></div><h3>どう答える？</h3><div class="choices">${counselChoices.map((x,i)=>`<button class="choice" data-counsel="${x[0]}"><b>${'ABCD'[i]}.</b> ${x[1]}</button>`).join('')}</div>`;return`<div class="section-title"><h2>${c.name}様への施術提案</h2><span class="pill">予算 ${yen(c.budget)}</span></div><p>お悩み「${c.concern}」に合う施術を選びましょう。</p><div class="service-list">${services.map(s=>`<button class="service ${!s.matches.includes(c.concern)?'bad':''}" data-service="${s.id}"><div style="font-size:30px">${s.icon}</div><b>${s.name}</b><div>${yen(s.price)}・${s.time}分</div>${s.matches.includes(c.concern)?'<span class="pill">おすすめ</span>':''}</button>`).join('')}</div>`}
function doService(id){const c=current(),s=services.find(x=>x.id===id),match=s.matches.includes(c.concern)?25:0,equip=(state.equipment.bed===3?5:state.equipment.bed===2?3:0)+(state.equipment.sofa>1?3:0)+(state.equipment.plant>1?2:0),price=s.price>c.budget?c.priceSensitivity*4:0,score=Math.max(0,Math.min(100,Math.round(s.base+state.staff.service*.22+state.staff.tech*.22+match+equip+state.session.counsel.bonus-price)));const star=score>=90?5:score>=75?4:score>=60?3:score>=40?2:1;const trustChange=state.session.counsel.trust+(match?5:-3)-(price?3:0);c.trust=Math.max(0,Math.min(100,c.trust+trustChange));c.visits++;c.totalSpent+=s.price;c.repeatChance=Math.min(90,20+Math.floor(score*.35)+Math.floor(c.trust*.25)+(star-3)*3);c.isRepeater=c.isRepeater||Math.random()<c.repeatChance/100;state.money+=s.price;state.todaySales+=s.price;state.cumulativeSales+=s.price;const reviews=['悩みをちゃんと聞いてくれて安心できました！','自分に合った施術を提案してもらえました。','施術はよかったけど、少し営業が強かったです。','予算も考えてくれて嬉しかったです。'];state.session.results.push({name:c.name,service:s.name,sales:s.price,score,star,review:reviews[Math.floor(Math.random()*reviews.length)],repeat:c.isRepeater});state.screen='serviceResult';render()}
function serviceResult(){const r=state.session.results.at(-1);return`<div class="card result"><span class="pill">接客完了</span><div class="score" style="--score:${r.score}"><strong>${r.score}</strong></div><h2>${r.name}様の満足度</h2><div class="stars">${stars(r.star)}</div><div class="speech">「${r.review}」</div><div class="row"><span>施術</span><b>${r.service}</b></div><div class="row"><span>売上</span><b>${yen(r.sales)}</b></div><div class="row"><span>次回来店</span><b>${r.repeat?'リピーター候補♡':'判定なし'}</b></div><p><button class="primary" data-action="nextCustomer">${state.session.index+1<state.session.queue.length?'次のお客様へ':'閉店する'}</button></p></div>`}
function nextCustomer(){state.session.index++;state.session.counsel=null;if(state.session.index>=state.session.queue.length)closeDay();else{state.screen='play';render()}}
function closeDay(){const rs=state.session.results,avg=Math.round(rs.reduce((a,x)=>a+x.score,0)/rs.length),reviews=rs.filter(()=>Math.random()<(state.ads.some(x=>x.id==='review')?.85:.5)),avgStars=reviews.length?reviews.reduce((a,x)=>a+x.star,0)/reviews.length:state.rating;state.rating=Math.max(1,Math.min(5,state.rating*.8+avgStars*.2));const popDelta=Math.round((avg-55)/4)+reviews.filter(x=>x.star>=4).length*3;state.popularity=Math.max(0,state.popularity+popDelta);state.xp+=rs.length*10+Math.floor(state.todaySales/1000)+reviews.filter(x=>x.star>=4).length*5;state.salonLevel=Math.min(10,1+Math.floor(state.xp/100));let expenses=0;if(state.day%30===0){expenses=state.staff.salary;state.money-=expenses}const entry={day:state.day,guests:rs.length,sales:state.todaySales,expenses,profit:state.todaySales-expenses,avg,reviews:reviews.length,repeaters:rs.filter(x=>x.repeat).length,popDelta};state.history.push(entry);state.ads=[];state.screen='dayResult';save();render()}
function dayResult(){const x=state.history.at(-1);return`<div class="section-title"><h2>Day ${x.day} 営業結果</h2><span class="pill">おつかれさまでした</span></div><div class="card result"><h1>${yen(x.sales)}</h1><p>本日の売上</p><div class="row"><span>来店人数</span><b>${x.guests}名</b></div><div class="row"><span>施術売上</span><b>${yen(x.sales)}</b></div><div class="row"><span>その他支出</span><b>−${yen(x.expenses)}</b></div><div class="row"><span>本日の利益</span><b>${yen(x.profit)}</b></div><div class="row"><span>口コミ投稿数</span><b>${x.reviews}件</b></div><div class="row"><span>平均満足度</span><b>${x.avg}</b></div><div class="row"><span>リピーター候補</span><b>${x.repeaters}名</b></div><div class="row"><span>店舗人気</span><b>${x.popDelta>=0?'+':''}${x.popDelta}</b></div><p><button class="primary" data-action="nextDay">翌日へ進む</button></p></div>`}
function render(){let body=state.screen==='home'?home():state.screen==='staff'?staffPage():state.screen==='services'?servicesPage():state.screen==='store'?store():state.screen==='ads'?ads():state.screen==='shop'?shop():state.screen==='customers'?customers():state.screen==='data'?data():state.screen==='play'?play():state.screen==='serviceResult'?serviceResult():dayResult();document.querySelector('#app').innerHTML=layout(body);bind()}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));document.querySelector('[data-action="start"]')?.addEventListener('click',startDay);document.querySelectorAll('[data-hire]').forEach(b=>b.onclick=()=>{state.staff=copy(staffOptions.find(x=>x.id===b.dataset.hire));save();notify(`${state.staff.name}を採用しました`)});document.querySelectorAll('[data-train]').forEach(b=>b.onclick=()=>{if(spend(+b.dataset.cost)){const gain=3+Math.floor(Math.random()*3),k=b.dataset.train;state.staff[k]=Math.min(100,state.staff[k]+gain);save();notify(`${gain}ポイント成長しました`)}});document.querySelectorAll('[data-ad]').forEach(b=>b.onclick=()=>{const a=adList.find(x=>x[0]===b.dataset.ad);if(spend(a[2])){state.ads.push({id:a[0],min:a[4],max:a[5]});save();notify(`${a[1]}を設定しました`)}});document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const x=shopItems.find(x=>x[0]===b.dataset.buy);if(spend(x[2])){state.equipment[x[0]]=x[4];save();notify(`${x[1]}を購入しました`)}});document.querySelectorAll('[data-counsel]').forEach(b=>b.onclick=()=>{const x=counselChoices.find(x=>x[0]===b.dataset.counsel);state.session.counsel={id:x[0],trust:x[2],bonus:x[3]+(x[0]==='sales'?(state.staff.sales/20-current().salesTolerance):-0)};render()});document.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>doService(b.dataset.service));document.querySelector('[data-action="nextCustomer"]')?.addEventListener('click',nextCustomer);document.querySelector('[data-action="nextDay"]')?.addEventListener('click',()=>{state.day++;state.todaySales=0;state.session=null;state.screen='home';save();render()});document.querySelector('[data-action="reset"]')?.addEventListener('click',()=>{if(confirm('すべてのセーブデータを削除しますか？')){localStorage.removeItem(KEY);state=initial();render()}})}render();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
