import{businessEvents,customerConditions,weatherTypes}from'./data/v06.js';

const pick=(items,rng)=>items[Math.min(items.length-1,Math.floor(rng()*items.length))];
export const seasonForDay=day=>['春','夏','秋','冬'][Math.floor(((day-1)%120)/30)];
export function createDailyWeather(day,rng=Math.random){const seasonal={春:['sunny','cloudy','rain'],夏:['sunny','hot','rain'],秋:['sunny','cloudy','rain'],冬:['sunny','cold','cloudy']}[seasonForDay(day)];return{...pick(weatherTypes.filter(x=>seasonal.includes(x.id)),rng)}}
export function dayAtmosphere(day,weekday){const monthDay=(day-1)%30+1;if(monthDay>=24)return'給料日後で美容需要UP';if(weekday==='土曜日')return'週末のお出かけ需要UP';if(weekday==='日曜日')return'ブライダル・家族イベントの日';if(weekday==='水曜日')return'主婦層の予約が増えそう';return`${seasonForDay(day)}の美容需要は安定しています`}
export function dailyGuestAdjustment({weekday,weather,policy}){let value=weekday==='月曜日'?-1:weekday==='土曜日'?1:0;value+=Number(weather?.guest||0)+Number(policy?.effects?.guest||0);return value}
export function pickCustomerCondition(customer,rng=Math.random){let pool=customerConditions;if(customer?.concern==='ブライダル美容')pool=[...customerConditions.filter(x=>['wedding-guest','photo','event','reward'].includes(x.id)),...customerConditions];const condition=pick(pool,rng);return{...condition}}
export function effectiveBudget(customer,condition){return Math.max(1000,Math.round((customer?.budget||0)*(condition?.budget||1)))}
export function conditionServiceBonus(condition,service,customer){if(!condition)return 0;const matched=condition.targets?.some(target=>service?.matches?.includes(target));return matched?condition.serviceBonus||0:condition.bonus||0}
export function selectBusinessEvents({day=1,rng=Math.random,max=3}={}){const count=Math.min(max,1+(rng()>.58?1:0)+(rng()>.88?1:0)),pool=[...businessEvents],picked=[];while(picked.length<count&&pool.length){const index=Math.floor(rng()*pool.length);picked.push(pool.splice(index,1)[0])}return picked.map(event=>({...event,day}))}
export function applyEventEffects(state,effects={}){state.money=Math.max(0,state.money+Number(effects.money||0));state.popularity=Math.max(0,state.popularity+Number(effects.popularity||0));if(state.staff)state.staff.energy=Math.max(0,Math.min(100,state.staff.energy+Number(effects.energy||0)));return{money:Number(effects.money||0),popularity:Number(effects.popularity||0),energy:Number(effects.energy||0),satisfaction:Number(effects.satisfaction||0),trust:Number(effects.trust||0),repeat:Number(effects.repeat||0),review:Number(effects.review||0)}}
export function nextDayPreview({day,reservations=[],rivalsUnlocked=false}){const nextDay=day+1,weekdays=['月曜日','火曜日','水曜日','木曜日','金曜日','土曜日','日曜日'],weekday=weekdays[(nextDay-1)%7];if(reservations.length)return`明日は${weekday}。${reservations[0].time}に予約が入っています。`;if(rivalsUnlocked&&nextDay%4===0)return`明日は${weekday}。ライバル店から新しい動きがありそうです。`;return`明日は${weekday}。${weekday==='土曜日'?'美容需要が高まりそうです。':'新しい出会いが待っていそうです。'}`}
